server:
  port: 8000

spring:
  application:
    # 应用名称
    name: sptr-gateway
  cloud:
    client:
      ip-address: 127.0.0.1
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）
        - id: sptr-item
          uri: http://localhost:8003
          predicates:
          - Path=/item/**
          filters:
          - PrefixPath=/sptr
        # 路由标识（id：标识，具有唯一性）
        - id: sptr-user
          uri: http://localhost:8002
          predicates:
          - Path=/user/**
          filters:
          - PrefixPath=/sptr
        #认证服务路由
        - id: sptr-auth
          uri: http://localhost:8001
          predicates:
          - Path=/auth/**
          filters:
            - PrefixPath=/sptr

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/

logging:
  level:
    root: INFO