server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://119.3.38.50:3306/sptr?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    #单机版
    #    host: 127.0.0.1
    #    port: 6379
    #    password: 123456
    #      pool:
    #        max-idle: 100
    #        min-idle: 1
    #        max-active: 1000
    #        max-wait: -1
    #集群版
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes:
        - 172.18.20.117:7001
        - 172.18.20.117:7002
        - 172.18.20.117:7003
        - 172.18.20.117:7004
        - 172.18.20.117:7005
        - 172.18.20.117:7006